computerclubkec/computerclubkec.github.io

- Dockerfile
- Gemfile.lock
- docker-compose.yml
This PR resolves #3 by adding the docker file and docker compose file.
> Add docker file and docker compose file

- README.md
I've updated README.MD file and which is yet to be updated but since I have made a layout, it'd be easier later.
> README.MD file updated

- README.md
This PR resolves #2 
A link to the website prototype has been added to the readme.md file.
> docs: add link of website prototype to readme.md

- README.md
This PR will add the link to the computer club for all the social handles.
> Add the Computer Club's linktree

- .github/workflows/vercel-pr-preview.yml
- .gitignore
This PR will resolve #24 
- created vercel-pr-review.yml file in github workflows
- created action secret variables
- authorised vercel with computer club's mail
> Implement vercel deployment for PR

- _layouts/home.html
This PR resolves #29.
- I have added flex to the banner div
- Reduced the size of the font for smaller screen
https://github.com/user-attachments/assets/104b094b-07da-46c5-b7d6-d5d812e93b82
> fix: add flex box and reduce the size of the font for smaller screen

- _config.yml
- _includes/footer.html
- _includes/nav.html
- _layouts/default.html
- _layouts/home.html
This PR resolves #31 issue.
Update the UI of the footer:
prev:
updated:
> update:ui of the footer acc to design

- README.md
This PR resolves #35. 
This makes it easier to extract and read the code from the README.md file for contributors.
> fix: enhance the code readability and extraction

- _layouts/home.html
This PR resolves #33 issue
- added the metric bar
- made it responsive
> feat: add metrics banner

- _includes/brands_colab.html
- _layouts/home.html
**This Pull Request resolves issue #38**
- brands colabration section
- makes it responsive
https://github.com/user-attachments/assets/9672c92a-edb8-45ac-ab5e-ce0c58891711
> feat: add brand colabration section

- _layouts/home.html
This is a fix to issue #59
I added section tags for upcoming events, brands-colab, and metrics-banner on the home page.
> added proper section tags with appropriate IDs

- _data/members.yml
- _includes/executive-member.html
- _includes/executive-members.html
- _layouts/home.html
- assets/js/main.js
> feat: add executive members section

- _config.yml
- contact.markdown
- Added Contact Us page
- Closes #68 
> Send button just logs the content of form
> `Contact Us` feels like a better header than `Contact Details`
> Contact page added

- _includes/nav.html
- assets/js/navbar/active.page.js
- Fixed the breakdown of `Contact us` button on smaller screens.
- Made all the font-size uniform as the website font-size.
- Also, fixes #46 & #64 
https://github.com/user-attachments/assets/2aa8aba6-9db9-4891-9971-2b345ddbaee6
https://github.com/user-attachments/assets/eb4fa6d6-e42a-4e60-84b7-64bc94dff31a
> fix: make nav bar responsive and uniform text size

- _includes/executive-members.html
Closes #76 
[Screencast from 10-12-2024 12:02:43 AM.webm](https://github.com/user-attachments/assets/b10bee89-1119-4a07-8ff7-12811a2b552f)
[Screencast from 10-12-2024 12:14:32 AM.webm](https://github.com/user-attachments/assets/0cda17d8-aa5c-49de-8d08-feeb6c34b7df)
> minor UI fix

- _includes/header.html
- _layouts/default.html
- _layouts/home.html
This PR resolves #80.
**Visually there is no change, since this is a refactor PR**
> refactor: create an include for header

- _includes/nav.html
As Per the issue #82 , I have added the hyperlink at the NavBar Logo to the root path.
> Added the link to Home at the navbar Logo 

- _config.yml
- _events/2024-10-01-learning-utsav.markdown
- _events/2024-11-10-tech-symposium-2024.markdown
- _events/2024-11-15-web-development-workshop.markdown
- _events/2024-11-20-coding-bootcamp-2024.markdown
- _events/2024-12-01-hack-a-lite.markdown
- _events/2024-12-05-ai-machine-learning-seminar.markdown
- _events/2024-12-15-mobile-app-development-contest.markdown
- _events/2024-12-20-cybersecurity-workshop.markdown
- _includes/recent-events.html
- _layouts/event.html
This PR resolves #55.
- _config.yml: Updated permalink structure for event collections.
- Add Event Layout
- Add some some dummy events for now.
The content part of the event can be manually styled in the markdown file, which gives flexibility for the content to be displayed the way we want.
Feel free to suggest any changes.
> feat: add event layout

- contact.markdown
> `mailto: ` seems to works differently on different browsers and with different mailing apps. So switched to gmail popup.
- Please try this to see if it works across different browser you use @RakeshPandey0 @prabhavpokharel @gaurovgiri
Closes #71
> Can Send mail from contact page

- _includes/nav.html
- assets/js/navbar/active.page.js
Closes #86 
> See #86 for problem
- Result:
> contact button ui fix

- _data/contributors.yml
- _includes/open-source-contributors.html
- about.markdown
This PR resolves #91 
- Added `about us` page.
- Created a `contributors.yml` file just like members.
Here's how the page looks.
Large Screens:
Small Screens:
> feat: add about us page

- _events/2024-10-01-learning-utsav.markdown
- _events/2024-11-10-tech-symposium-2024.markdown
- _events/2024-11-15-web-development-workshop.markdown
- _events/2024-11-20-coding-bootcamp-2024.markdown
- _events/2024-12-01-hack-a-lite.markdown
- _events/2024-12-05-ai-machine-learning-seminar.markdown
- _events/2024-12-15-mobile-app-development-contest.markdown
- _events/2024-12-20-cybersecurity-workshop.markdown
- _events/YYYY-MM-DD-example-title.markdown
- _events/kec-lite.markdown
- _includes/nav.html
- _includes/recent-events.html
- _includes/upcoming-events.html
- _layouts/event.html
- past-events.markdown
- Closes #104 
- Made some changes for #101 but i think the page requires some redesign from @prabhavpokharel Closes #101
- This is how it looks after changes:
> Event layout update

- 404.html
> update error page with home button

- _includes/nav.html
This PR resolves #117 
Added a menu item in the event's dropdown for "Request an Event".
The nav bar's height was too large for a smaller screen and too short for a medium screen. I've fixed that, too.
Before:
After:
Before:
After:
> feat: add 'request an event' menu item and adjust the height of nav bar

- _includes/nav.html
Solves #134
- Added a sticky property to the navigation bar, allowing it to remain fixed at the top of the viewport as the user scrolls.
- Ensured that the navbar’s styling remains consistent across different screen sizes and devices, enhancing user accessibility and navigation.
Navbar remains fixed at the top of the viewport as seen below:
> enhancement: add sticky navbar functionality

- _layouts/home.html
- assets/js/main.js
**Title:** Implement Carousel Effect for Metrics Banner
**Description:**  
This PR introduces a carousel effect for the metrics banner component. Previously static, the metrics now dynamically cycle, enhancing user engagement.
Also resolves #131 for metric section only.
**Key Changes:**
- Added carousel functionality for key metrics.
- On smaller screen: displays 1 metric at a time.
---
**Before:**  
- Static display of metrics without interactivity.
**After:**  
- Dynamic carousel showcasing metrics, improving engagement.
https://github.com/user-attachments/assets/5bd24e50-4190-4e2e-b544-fd84e000ecab
This update enhances the responsiveness and interactivity of the metrics banner. Please review and provide feedback. Thank you!
> feat:add carousel effect for metric banner in smaller screen

- _includes/executive-members-list.html
- _includes/executive-members.html
- about.markdown
- So as requested all the indication for the year has been removed from the home screen, now home screen only shows the the active members list.
- Second thing is a new `executive-members-list` file has been added,  making it easy to modify the list of members in upcoming years.
> Added fixes for issue #128

- _includes/header.html
This PR will add club's name in the title for each page separated by `|`.
> include club name in the title

- _includes/nav.html
- about.markdown
- blog.markdown
- contact.markdown
- event.markdown
- resources.markdown
**Summary**  
This PR resolves link and path issues on the website and standardizes permalink naming conventions. Fixes #143.
**Changes Made**  
- Replaced all incorrect or broken links.
- Standardized permalink naming for consistency.
- Added links for resources such as "roadmaps," "brand assets," and "proposal format."
- Fixed image path on the "About Us" page by correcting the folder structure.
Before:
After:
> hotfix: update links, standardize permalinks, and resolve image path issue

- 404.html
- _events/kec-lite.markdown
- _includes/brands_colab.html
- _includes/executive-members-list.html
- _includes/executive-members.html
- _includes/footer.html
- _includes/header.html
- _includes/hero-section.html
- _includes/nav.html
- _includes/open-source-contributors.html
- _includes/projects_section.html
- _includes/recent-events.html
- _includes/upcoming-events.html
- _layouts/blog.html
- _layouts/default.html
- _layouts/event.html
- about.markdown
- assets/js/tailwind.config.js
- contact.markdown
- past-events.markdown
- projects.markdown
- upcoming-events.markdown
**Description**:
This PR resolves the missing font family issue by integrating the required Montserrat and Inter fonts as per the design specifications. Fixes issue #21. 
1. **Google Fonts Integration**: Added a Google Fonts link in the header to load Montserrat and Inter fonts.
2. **Tailwind Configuration Update**: Updated `tailwind.config.js` to recognize Montserrat and Inter, enabling the use of `font-[Montserrat]` and `font-[Inter]` classes.
3. **Content Update**: Applied the new font pair (Montserrat and Inter) across all content, ensuring consistency with design requirements.
This update aligns typography with design guidelines and enhances site aesthetics.
Before: 
After:
> fix: font family issue

- LICENSE
**Description:**  
This PR introduces a `LICENSE` file to the repository, applying the MIT License. This open-source license allows contributors and users to freely use, modify, and distribute the code under specific terms.
**Changes Made:**  
- Added `LICENSE` file with the MIT License text.
**Issue Reference:**  
Closes #148
> add MIT license to the project

- _config.yml
- _includes/footer.html
- about.markdown
- contact.markdown
TikTok and Discord links of KEC Computer Club are added with this PR.
> feat: add all social media profile links
